name: Floris van Buren
favicon: null
layout_spectrum: 0.70646
typography_spectrum: 0.43764705676585436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#28344c'
    - '#5e6673'
    - '#90938e'
    - '#b5bbc5'
  brandStrength: 0.8207345362752676
  lightness: 0.7828980926424265
  saturation: 0.8758218146394938
  rhythmicContrast: 0.04653670405969024
purpose: []
